<?php

use Illuminate\Database\Seeder;
use App\Models\Admin\Currency;

class CurrencySeeder extends Seeder {

  private $data = [
      ['code' => 'ADP' , 'name' => 'Peseta Andorrana'],
      ['code' => 'AED' , 'name' => 'Dirham de los Emiratos Árabes Unidos'],
      ['code' => 'AFA' , 'name' => 'Afghani'],
      ['code' => 'ALL' , 'name' => 'Lek Albanés'],
      ['code' => 'AMD' , 'name' => 'Dram Armenio'],
      ['code' => 'ANG' , 'name' => 'Guilder de India Occidental'],
      ['code' => 'AOK' , 'name' => 'Kwanza Angolés'],
      ['code' => 'ARA' , 'name' => 'Austral Argentino'],
      ['code' => 'ARS' , 'name' => 'Peso Argentino'],
      ['code' => 'ATS' , 'name' => 'Chelín Austriaco'],
      ['code' => 'AUD' , 'name' => 'Dólar Australiano'],
      ['code' => 'AWG' , 'name' => 'Guilder de Aruba'],
      ['code' => 'AZM' , 'name' => 'Manat de Azerbaijan'],
      ['code' => 'BAD' , 'name' => 'Dinar de Bosnia-Herzogovinia'],
      ['code' => 'BBD' , 'name' => 'Dólar de Barbados'],
      ['code' => 'BDT' , 'name' => 'Taka de Bangladesh'],
      ['code' => 'BEF' , 'name' => 'Franco Belga'],
      ['code' => 'BGL' , 'name' => 'Lev Bulgaro'],
      ['code' => 'BHD' , 'name' => 'Dinar de Barein'],
      ['code' => 'BIF' , 'name' => 'Franco de Burundi'],
      ['code' => 'BMD' , 'name' => 'Dólar de Bermudas'],
      ['code' => 'BND' , 'name' => 'Dólar de Brunei'],
      ['code' => 'BOB' , 'name' => 'Boliviano de Bolivia'],
      ['code' => 'BRL' , 'name' => 'Real de Brazil'],
      ['code' => 'BRR' , 'name' => 'Brazil'],
      ['code' => 'BSD' , 'name' => 'Dólar de Bahamas'],
      ['code' => 'BWP' , 'name' => 'Pula de Botswana'],
      ['code' => 'BYR' , 'name' => 'Rublo de Belorusia'],
      ['code' => 'BZD' , 'name' => 'Dólar de Belize'],
      ['code' => 'CAD' , 'name' => 'Dólar Canadiense'],
      ['code' => 'CDP' , 'name' => 'Santo Domingo'],
      ['code' => 'CHF' , 'name' => 'Franco Suizo'],
      ['code' => 'CLP' , 'name' => 'Peso Chileno'],
      ['code' => 'CNY' , 'name' => 'China'],
      ['code' => 'COP' , 'name' => 'Peso de Colombia'],
      ['code' => 'CRC' , 'name' => 'Colon de Costa Rica'],
      ['code' => 'CUP' , 'name' => 'Peso Cubano'],
      ['code' => 'CVE' , 'name' => 'Escudo de Cabo Verde'],
      ['code' => 'CYP' , 'name' => 'Libra de Chipre'],
      ['code' => 'CZK' , 'name' => 'Krona Checa'],
      ['code' => 'DEM' , 'name' => 'Marco Alemán'],
      ['code' => 'DJF' , 'name' => 'Franco de Djibouti'],
      ['code' => 'DKK' , 'name' => 'Corona Danesa'],
      ['code' => 'DOP' , 'name' => 'Peso Dominicano'],
      ['code' => 'DRP' , 'name' => 'Peso de la República Dominicana'],
      ['code' => 'DZD' , 'name' => 'Dinar de Algeria'],
      ['code' => 'ECS' , 'name' => 'Sucre de Ecuador'],
      ['code' => 'ECU' , 'name' => 'Moneda Única Europea (EURO)'],
      ['code' => 'EEK' , 'name' => 'Corona de Estonia'],
      ['code' => 'EGP' , 'name' => 'Libra Egipcia'],
      ['code' => 'ESP' , 'name' => 'Peseta Española'],
      ['code' => 'ETB' , 'name' => 'Birr de Etiopía'],
      ['code' => 'EUR' , 'name' => 'Moneda de los estados miembros de EMU'],
      ['code' => 'FIM' , 'name' => 'Marco Finlandés'],
      ['code' => 'FJD' , 'name' => 'Dólar de Fiji'],
      ['code' => 'FKP' , 'name' => 'Libra de Falkland'],
      ['code' => 'FRF' , 'name' => 'Franco Francés'],
      ['code' => 'GBP' , 'name' => 'Libra Británica'],
      ['code' => 'GEK' , 'name' => 'Kupon de Georgia'],
      ['code' => 'GHC' , 'name' => 'Cedi de Ghana'],
      ['code' => 'GIP' , 'name' => 'Libra de Gibraltar'],
      ['code' => 'GMD' , 'name' => 'Dalasi de Gambia'],
      ['code' => 'GNF' , 'name' => 'Franco de Guinea'],
      ['code' => 'GRD' , 'name' => 'Dracma Griego'],
      ['code' => 'GTQ' , 'name' => 'Quedzal de Guatemala'],
      ['code' => 'GWP' , 'name' => 'Peso de Guinea'],
      ['code' => 'GYD' , 'name' => 'Dólar Guayanés'],
      ['code' => 'HKD' , 'name' => 'Dólar de Hong Kong'],
      ['code' => 'HNL' , 'name' => 'Lempira de Honduras'],
      ['code' => 'HRD' , 'name' => 'Dinar de Croacia'],
      ['code' => 'HTG' , 'name' => 'Gourde de Haiti'],
      ['code' => 'HUF' , 'name' => 'Florín Húngaro'],
      ['code' => 'IDR' , 'name' => 'Rupia Indonesia'],
      ['code' => 'IEP' , 'name' => 'Libra Irlandesa'],
      ['code' => 'ILS' , 'name' => 'Scheckel Israelí'],
      ['code' => 'INR' , 'name' => 'Rupia India'],
      ['code' => 'IQD' , 'name' => 'Dinar Iraquí'],
      ['code' => 'IRR' , 'name' => 'Rial Iraní'],
      ['code' => 'ISK' , 'name' => 'Corona Islandesa'],
      ['code' => 'ITL' , 'name' => 'Lira Italiana'],
      ['code' => 'JMD' , 'name' => 'Dólar de Jamaica'],
      ['code' => 'JOD' , 'name' => 'Dinar de Jordania'],
      ['code' => 'JPY' , 'name' => 'Yen Japonés'],
      ['code' => 'KES' , 'name' => 'Chelín de Kenya'],
      ['code' => 'KHR' , 'name' => 'Riel de Camboya'],
      ['code' => 'KIS' , 'name' => 'Som de Kirghizstan'],
      ['code' => 'KMF' , 'name' => 'Franco de Comoros'],
      ['code' => 'KPW' , 'name' => 'Won de Corea del Norte'],
      ['code' => 'KRW' , 'name' => 'Won de Corea del Sur'],
      ['code' => 'KWD' , 'name' => 'Dinar de Kuwait'],
      ['code' => 'KYD' , 'name' => 'Dólar de las Caimán'],
      ['code' => 'KZT' , 'name' => 'Tenge de Kazakhstán'],
      ['code' => 'LAK' , 'name' => 'Kip de Letonia'],
      ['code' => 'LBP' , 'name' => 'Libra Libanesa'],
      ['code' => 'LKR' , 'name' => 'Rupia de Ceilán'],
      ['code' => 'LRD' , 'name' => 'Dólar de Liberia'],
      ['code' => 'LSL' , 'name' => 'Loti de Lesotho'],
      ['code' => 'LTL' , 'name' => 'Lita de Lituania'],
      ['code' => 'LUF' , 'name' => 'Franco de Luxemburgo'],
      ['code' => 'LVL' , 'name' => 'Lat Latonia'],
      ['code' => 'LYD' , 'name' => 'Dinar Libio'],
      ['code' => 'MAD' , 'name' => 'Dirham Marroquí'],
      ['code' => 'MDL' , 'name' => 'Lei de Moldavia'],
      ['code' => 'MGF' , 'name' => 'Franco de Madagascar'],
      ['code' => 'MNC' , 'name' => 'Monaco'],
      ['code' => 'MNT' , 'name' => 'Tugrik de Mongolia'],
      ['code' => 'MOP' , 'name' => 'Pataca de Macao'],
      ['code' => 'MRO' , 'name' => 'Ouguiya de Mauritania'],
      ['code' => 'MTL' , 'name' => 'Lira de Malta'],
      ['code' => 'MUR' , 'name' => 'Rupia de "Mauritius"'],
      ['code' => 'MVR' , 'name' => 'Rufia de Maldivas'],
      ['code' => 'MWK' , 'name' => 'Kwacha de Malawi'],
      ['code' => 'MXN' , 'name' => 'Peso Mexicano (nuevo)'],
      ['code' => 'MXP' , 'name' => 'Peso Mexicano (viejo)'],
      ['code' => 'MYR' , 'name' => 'Ringgit de Malaysia'],
      ['code' => 'MZM' , 'name' => 'Metical de Mozambique'],
      ['code' => 'NGN' , 'name' => 'Naira de Nigeria'],
      ['code' => 'NIC' , 'name' => 'Nicaragua'],
      ['code' => 'NIO' , 'name' => 'Cordoba de Nicaragua'],
      ['code' => 'NIS' , 'name' => 'Isreal'],
      ['code' => 'NLG' , 'name' => 'Guilder de Holanda'],
      ['code' => 'NOK' , 'name' => 'Córona Noruega'],
      ['code' => 'NPR' , 'name' => 'Rupia de Nepal'],
      ['code' => 'NZD' , 'name' => 'Dólar de Nueva Zelanda'],
      ['code' => 'OMR' , 'name' => 'Rial de Omán'],
      ['code' => 'PAB' , 'name' => 'Balboa de Panamá'],
      ['code' => 'PEI' , 'name' => 'Inti de Perú'],
      ['code' => 'PEN' , 'name' => 'Sol de Perú - Nuevo'],
      ['code' => 'PES' , 'name' => 'Sol de Perú'],
      ['code' => 'PGK' , 'name' => 'Kina de Papua Nueva Guinea'],
      ['code' => 'PHP' , 'name' => 'Peso Filipino'],
      ['code' => 'PKR' , 'name' => 'Rupia de Pakistán'],
      ['code' => 'PLN' , 'name' => 'Zloty de Polonia'],
      ['code' => 'PLZ' , 'name' => 'Polonia'],
      ['code' => 'PTE' , 'name' => 'Escudo Portugués'],
      ['code' => 'PYG' , 'name' => 'Guarani de Paraguay'],
      ['code' => 'QAR' , 'name' => 'Riyal de Qatar'],
      ['code' => 'RMB' , 'name' => 'Remnminbi Yuan de China'],
      ['code' => 'ROL' , 'name' => 'Lei de Rumania'],
      ['code' => 'RUR' , 'name' => 'Rublo Ruso'],
      ['code' => 'RWF' , 'name' => 'Franco de Rwanda'],
      ['code' => 'SAR' , 'name' => 'Riyal de Arabia Saudí'],
      ['code' => 'SBD' , 'name' => 'Dólar de las Islas Solomon'],
      ['code' => 'SCR' , 'name' => 'Rupias de Seychelles'],
      ['code' => 'SDP' , 'name' => 'Libra de Sudán'],
      ['code' => 'SEK' , 'name' => 'Córona Sueca'],
      ['code' => 'SGD' , 'name' => 'Dólar de Singapur'],
      ['code' => 'SHP' , 'name' => 'Libra de St.Helena'],
      ['code' => 'SIT' , 'name' => 'Tolar de Eslovenia'],
      ['code' => 'SKK' , 'name' => 'Córona Eslovaca'],
      ['code' => 'SLL' , 'name' => 'Sierra León'],
      ['code' => 'SOL' , 'name' => 'Perú'],
      ['code' => 'SOS' , 'name' => 'Chellín de Somalia'],
      ['code' => 'SRG' , 'name' => 'Guilder de Surinam'],
      ['code' => 'STD' , 'name' => 'Sao Tome / Principe Dobra'],
      ['code' => 'SUR' , 'name' => 'Rublo Ruso (viejo)'],
      ['code' => 'SVC' , 'name' => 'Colon de El Salvador'],
      ['code' => 'SYP' , 'name' => 'libra de Siria'],
      ['code' => 'SZL' , 'name' => 'Lilangeni de Swaziland'],
      ['code' => 'THB' , 'name' => 'Baht de Tailandia'],
      ['code' => 'TJR' , 'name' => 'Rublo de Tadzikistán'],
      ['code' => 'TMM' , 'name' => 'Manat de Turkmenistán'],
      ['code' => 'TND' , 'name' => 'Dinar de Tunícia'],
      ['code' => 'TOP' , 'name' => 'Pa\'anga de Tonga'],
      ['code' => 'TPE' , 'name' => 'Escudo de Timor'],
      ['code' => 'TRL' , 'name' => 'Lira de Turquía'],
      ['code' => 'TTD' , 'name' => 'Dólar de Trinidad y Tobagor'],
      ['code' => 'TWD' , 'name' => 'Dólar de Nuevo Taiwán'],
      ['code' => 'TZS' , 'name' => 'Chellín de Tanzania'],
      ['code' => 'UAK' , 'name' => 'karbowanez de Ucrainia'],
      ['code' => 'UGS' , 'name' => 'Chellín de Uganda'],
      ['code' => 'USD' , 'name' => 'Dólar Americano'],
      ['code' => 'UYP' , 'name' => 'Nuevo Peso de Uruguay'],
      ['code' => 'UYU' , 'name' => 'Uruguay'],
      ['code' => 'VEB' , 'name' => 'Bolivar de Venezuela'],
      ['code' => 'VND' , 'name' => 'Dong de Vietnám'],
      ['code' => 'VUV' , 'name' => 'Vatu de Vanuatu'],
      ['code' => 'WST' , 'name' => 'Tala de Samoa'],
      ['code' => 'XAF' , 'name' => 'Franco de Gabón'],
      ['code' => 'XCD' , 'name' => 'Dólar de Caribe Oriental'],
      ['code' => 'XOF' , 'name' => 'Franco de Benin (C.f.A.)'],
      ['code' => 'YER' , 'name' => 'Ryal de Yemen'],
      ['code' => 'ZAR' , 'name' => 'Rand de Sur África'],
      ['code' => 'ZMK' , 'name' => 'Kwacha de Zambia'],
      ['code' => 'ZRZ' , 'name' => 'Zaire'],
      ['code' => 'ZWD' , 'name' => 'Dólar de Zimbawe']
  ];

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run() {
    foreach ($this->data as $key => $row) {
      Currency::create([
        'code'      => $row['code'],
        'name'      => $row['name']
      ]);
    }
  }
}
